### ISSUE TITLE
getting FIN from file

### ISSUE THREAD

**Issue by NP199** [skunkforce/OmniView#25]
When you save the file, the FIN must be written into one textfield. When you click on create training data you have to retype  the FIN. Either the FIN is loaded from the file name you load into the create training data field or you could make a new funcion which loads the FIN from the VCDS file.

**Comment by bjoekeldude** [comment]
Is there a convention, how these files should be formatted? 
Right now, there is no __Header__ or __Meta-Section__ inside the file, correct?

We should save Data JSON-like.
{
   "meta":........,
   "data":[session-timestamp, ]
}
Session-Timestamp should probably be seconds after start of application. Otherwise we could potentially use Unix-Timestamps.

Furthermore every Session should get a unique ID in UUIDv4 Format. Multiple Channels should be saved as separate files, sharing the same "meta":"session"=UUID.

**Comment by NP199** [comment]
Right now the files are just saved as a simple csv file.
I got some feedback and some people like this simplicity so they can jsut plot the data to look at them at a later stage in the diagnostic.
Maybe we should not change the file format for now until we add a feature to reinterpret the saved data into another or the same graph.

My idea was to add a function in omniview to extract the VIN from an VCDS file. Typing the VIN is error prone and takes unnecessary time.

**Comment by AKMaily** [comment]
The first problem will be solved by adding a local variable that saves the VIN when the user saves the measurement or sends the measurement to the API. The value of the variable is then automatically inserted into all appropriate fields and is deleted as soon as the user resets the measurement.
